/-
Copyright (c) 2025 Bhavik Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bhavik Mehta, Kevin Buzzard
-/
import Mathlib.Tactic
-- imports all the Lean tactics
import Mathlib.MeasureTheory.MeasurableSpace.Defs

/-

# Measure theory

## Sigma algebras.

A σ-algebra on a type `X` is a collection of subsets of `X` satisfying some
axioms, and in Lean you write it like this:

-/

namespace Section13Sheet1

-- let X be a set
variable (X : Type)

-- ...and let 𝓐 be a sigma-algebra on X
variable (𝓐 : MeasurableSpace X)

/-

Note that `MeasurableSpace` is a *class*, so really we should be writing `[MeasurableSpace X]`,
meaning "let `X` be equipped once and for all with a sigma algebra which we won't give a name to".
But in this sheet we'll consider making them explicitly.

Let's do the following exercise. Show that if `A` is a subset of `X` then `{0,A,Aᶜ,X}`
is a sigma algebra on `X`.

-/
def genBy (A : Set X) : MeasurableSpace X where
  MeasurableSet' S := S = ∅ ∨ S = A ∨ S = Aᶜ ∨ S = Set.univ
  measurableSet_empty := by simp
  measurableSet_compl := by
    rintro s (rfl | rfl | rfl | rfl) <;> simp
  measurableSet_iUnion f hf := by
    by_cases h_univ : ∃ i, f i = Set.univ
    · right; right; right; rcases h_univ with ⟨i, hi⟩
      exact Set.univ_subset_iff.mp (hi ▸ Set.subset_iUnion f i)
    push_neg at h_univ
    by_cases h_both : (∃ i, f i = A) ∧ (∃ j, f j = Aᶜ)
    · right; right; right; rcases h_both with ⟨⟨i, hi⟩, ⟨j, hj⟩⟩
      apply Set.univ_subset_iff.mp
      intro x _
      by_cases hx : x ∈ A
      · exact Set.mem_iUnion.mpr ⟨i, hi.symm ▸ hx⟩
      · exact Set.mem_iUnion.mpr ⟨j, hj.symm ▸ hx⟩
    · by_cases h_A : ∃ i, f i = A
      · right; left; apply Set.Subset.antisymm
        · rintro x hx; rcases Set.mem_iUnion.mp hx with ⟨i, hi⟩
          rcases hf i with rfl | rfl | rfl | rfl
          · contradiction
          · assumption
          · exfalso; apply h_both; exact ⟨h_A, ⟨i, rfl⟩⟩
          · contradiction
        · rcases h_A with ⟨i, hi⟩; rw [← hi]; exact Set.subset_iUnion f i
      · by_cases h_Ac : ∃ i, f i = Aᶜ
        · right; right; left; apply Set.Subset.antisymm
          · rintro x hx; rcases Set.mem_iUnion.mp hx with ⟨i, hi⟩
            rcases hf i with rfl | rfl | rfl | rfl
            · contradiction
            · exfalso; apply h_A; exact ⟨i, rfl⟩
            · assumption
            · contradiction
          · rcases h_Ac with ⟨i, hi⟩; rw [← hi]; exact Set.subset_iUnion f i
        · left; apply Set.Subset.antisymm
          · rintro x hx; rcases Set.mem_iUnion.mp hx with ⟨i, hi⟩
            rcases hf i with rfl | rfl | rfl | rfl
            · contradiction
            · exfalso; apply h_A; exact ⟨i, rfl⟩
            · exfalso; apply h_Ac; exact ⟨i, rfl⟩
            · contradiction
          · exact Set.empty_subset _

-- An alternative approach to defining the sigma algebra generated by `{A}` is just
-- to use `MeasurableSpace.generateFrom`:
example (A : Set X) : MeasurableSpace X :=
  MeasurableSpace.generateFrom {A}

-- But the problem with that approach is that you don't get the actual sets
-- in the sigma algebra for free. Try this, to see what I mean!
example (A : Set X) :
    (MeasurableSpace.generateFrom {A}).MeasurableSet' =
    ({∅, A, Aᶜ, Set.univ} : Set (Set X)) := by
  ext S
  constructor
  · intro h
    induction h with
    | basic s hs => simp at hs; subst hs; simp
    | empty => simp
    | compl s hs ih => rcases ih with rfl | rfl | rfl | rfl <;> simp
    | iUnion f hf ih =>
      by_cases h_univ : ∃ i, ih i = Set.univ
      · rcases h_univ with ⟨i, hi⟩
        have : (⋃ i, f i) = Set.univ := Set.univ_subset_iff.mp (hi ▸ Set.subset_iUnion f i)
        rw [this]; simp
      push_neg at h_univ
      by_cases h_both : (∃ i, ih i = A) ∧ (∃ j, ih j = Aᶜ)
      · rcases h_both with ⟨⟨i, hi⟩, ⟨j, hj⟩⟩
        have : (⋃ i, f i) = Set.univ := by
          apply Set.univ_subset_iff.mp; intro x _
          by_cases hx : x ∈ A
          · exact Set.mem_iUnion.mpr ⟨i, hi.symm ▸ hx⟩
          · exact Set.mem_iUnion.mpr ⟨j, hj.symm ▸ hx⟩
        rw [this]; simp
      · by_cases h_A : ∃ i, ih i = A
        · have : (⋃ i, f i) = A := by
            apply Set.Subset.antisymm
            · rintro x hx; rcases Set.mem_iUnion.mp hx with ⟨k, hk⟩
              specialize ih k; rcases ih with rfl | rfl | rfl | rfl
              · contradiction
              · exact hk
              · exfalso; apply h_both; exact ⟨h_A, ⟨k, rfl⟩⟩
              · contradiction
            · rcases h_A with ⟨i, hi⟩; rw [← hi]; exact Set.subset_iUnion f i
          rw [this]; simp
        · by_cases h_Ac : ∃ i, ih i = Aᶜ
          · have : (⋃ i, f i) = Aᶜ := by
              apply Set.Subset.antisymm
              · rintro x hx; rcases Set.mem_iUnion.mp hx with ⟨k, hk⟩
                specialize ih k; rcases ih with rfl | rfl | rfl | rfl
                · contradiction
                · exfalso; apply h_A; exact ⟨k, rfl⟩
                · exact hk
                · contradiction
              · rcases h_Ac with ⟨i, hi⟩; rw [← hi]; exact Set.subset_iUnion f i
            rw [this]; simp
          · have : (⋃ i, f i) = ∅ := by
              apply Set.Subset.antisymm
              · rintro x hx; rcases Set.mem_iUnion.mp hx with ⟨k, hk⟩
                specialize ih k; rcases ih with rfl | rfl | rfl | rfl
                · contradiction
                · exfalso; apply h_A; exact ⟨k, rfl⟩
                · exfalso; apply h_Ac; exact ⟨k, rfl⟩
                · contradiction
              · exact Set.empty_subset _
            rw [this]; simp
  · rintro (rfl | rfl | rfl | rfl)
    · exact MeasurableSpace.measurableSet_empty _
    · apply MeasurableSpace.GenerateMeasurable.basic; simp
    · apply MeasurableSpace.measurableSet_compl
      apply MeasurableSpace.GenerateMeasurable.basic; simp
    · exact MeasurableSpace.measurableSet_univ _

end Section13Sheet1